CMSBundle\Entity\Document:
    type: entity
    table: null
    repositoryClass: CMSBundle\Repository\DocumentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        path:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
