<?php

namespace CMSBundle\Repository;

/**
 * PoradyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoradyRepository extends \Doctrine\ORM\EntityRepository
{
}
