<?php

namespace CMSBundle\Repository;

/**
 * PromocjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocjeRepository extends \Doctrine\ORM\EntityRepository
{
}
